const express = require('express');
const AreaController = require('../controllers/AreaController');
const UsuarioController = require('../controllers/UsuarioController');
const DocentesController = require('../controllers/DocentesController');
const NotificacionesController = require('../controllers/NotificacionesController');
const PabellonesController = require('../controllers/PabellonesController');
const SalonesController = require('../controllers/SalonesController');
const AlumnosController = require('../controllers/AlumnosController');
const upload = require('../controllers/ImageMiddleware');
const UploadController = require('../controllers/UploadController');

const router = express.Router();

router.get('/areas', AreaController.getAll);
router.get('/areas/:id', AreaController.getById);
router.post('/login', UsuarioController.loginUser);
router.get('/finduser', UsuarioController.findUser);
router.post('/nuevoarea', AreaController.insertArea);
router.put('/editararea/:id', AreaController.updateArea);
router.delete('/nuevoarea', AreaController.deleteArea);
router.get('/buscarareas', AreaController.searchArea);
router.post('/uploads', upload.single('image'), UploadController.uploadImage);
router.delete('/uploads', UploadController.deleteImage);
router.get('/users', UsuarioController.getAllUsers);
router.get('/users/find', UsuarioController.getUser);
router.post('/users/verify', UsuarioController.verifyUser);
router.post('/users/create', UsuarioController.createUser);
router.delete('/users/delete/:id', UsuarioController.deleteUser);
router.put('/users/update/:id', UsuarioController.updateUser);
router.get('/docentes/filtrar', DocentesController.getAllDocentesMatching);
router.get('/docentes/lista', DocentesController.getAllDocentes);
router.get('/docentes/buscar', DocentesController.getDocente);
router.get('/docentes/estados', DocentesController.getEstados);
router.get('/notificaciones/filtrar', NotificacionesController.getByEmail);
router.get('/notificaciones/noleidas', NotificacionesController.getUnread);
router.get('/notificaciones/conteo', NotificacionesController.getUnreadCount);
router.delete('/notificaciones/borrar/:id', NotificacionesController.deleteNoti);
router.post('/notificaciones/nuevo', NotificacionesController.insertNoti);
router.get('/pabellones/lista', PabellonesController.getAllPabellones);
router.get('/pabellones/buscar/:id', PabellonesController.getPabellon);
router.post('/pabellones/nuevo', PabellonesController.insertPabellon);
router.put('/pabellones/editar/:id', PabellonesController.editPabellon);
router.delete('/pabellones/borrar/:id', PabellonesController.deletePabellon);
router.get('/salones/lista', SalonesController.getAllSalones);
router.get('/salones/filtrar', SalonesController.getAllSalonesByPabellon);
router.get('/salones/buscar/:id', SalonesController.getSalonById);
router.post('/salones/nuevo', SalonesController.insertSalon);
router.put('/salones/editar', SalonesController.editSalon);
router.delete('/salones/borrar/:id', SalonesController.deleteSalon);
router.get('/salones/conteo/:id', SalonesController.countSalonesByPabellon);
router.get('/alumnos/conteo', AlumnosController.countAlumnos);
router.get('/alumnos/listapag', AlumnosController.getAlumnosPaginated);

module.exports = router;