const express = require('express');
const AreaController = require('../controllers/AreaController');
const UsuarioController = require('../controllers/UsuarioController');
const DocentesController = require('../controllers/DocentesController');
const NotificacionesController = require('../controllers/NotificacionesController');
const PabellonesController = require('../controllers/PabellonesController');
const SalonesController = require('../controllers/SalonesController');
const AlumnosController = require('../controllers/AlumnosController');
const ReportesController = require('../controllers/ReportesController');
const AdminUsersController = require('../controllers/AdminUsersController');
const UserAreasController = require('../controllers/UserAreasController');
const upload = require('../controllers/ImageMiddleware');
const UploadController = require('../controllers/UploadController');

const router = express.Router();

router.get('/areas', AreaController.getAll);
router.get('/areas/:id', AreaController.getById);
router.post('/login', UsuarioController.loginUser);
router.get('/finduser', UsuarioController.findUser);
router.post('/nuevoarea', AreaController.insertArea);
router.put('/editararea/:id', AreaController.updateArea);
router.delete('/nuevoarea', AreaController.deleteArea);
router.get('/buscarareas', AreaController.searchArea);
router.post('/uploads', upload.single('image'), UploadController.uploadImage);
router.delete('/uploads', UploadController.deleteImage);
router.get('/users', UsuarioController.getAllUsers);
router.get('/users/find', UsuarioController.getUser);
router.post('/users/verify', UsuarioController.verifyUser);
router.post('/users/create', UsuarioController.createUser);
router.delete('/users/delete/:id', UsuarioController.deleteUser);
router.put('/users/update/:id', UsuarioController.updateUser);
router.get('/docentes/filtrar', DocentesController.getAllDocentesMatching);
router.get('/docentes/lista', DocentesController.getAllDocentes);
router.get('/docentes/buscar', DocentesController.getDocente);
router.get('/docentes/estados', DocentesController.getEstados);
router.get('/notificaciones/filtrar', NotificacionesController.getByEmail);
router.get('/notificaciones/noleidas', NotificacionesController.getUnread);
router.get('/notificaciones/conteo', NotificacionesController.getUnreadCount);
router.delete('/notificaciones/borrar/:id', NotificacionesController.deleteNoti);
router.post('/notificaciones/nuevo', NotificacionesController.insertNoti);
router.get('/pabellones/lista', PabellonesController.getAllPabellones);
router.get('/pabellones/buscar/:id', PabellonesController.getPabellon);
router.post('/pabellones/nuevo', PabellonesController.insertPabellon);
router.put('/pabellones/editar/:id', PabellonesController.editPabellon);
router.delete('/pabellones/borrar/:id', PabellonesController.deletePabellon);
router.get('/salones/lista', SalonesController.getAllSalones);
router.get('/salones/filtrar', SalonesController.getAllSalonesByPabellon);
router.get('/salones/buscar/:id', SalonesController.getSalonById);
router.post('/salones/nuevo', SalonesController.insertSalon);
router.put('/salones/editar', SalonesController.editSalon);
router.delete('/salones/borrar/:id', SalonesController.deleteSalon);
router.get('/salones/conteo/:id', SalonesController.countSalonesByPabellon);
router.get('/alumnos/conteo', AlumnosController.countAlumnos);
router.get('/alumnos/listapag', AlumnosController.getAlumnosPaginated);
router.get('/alumnos/lista', AlumnosController.getAllAlumnos);
router.get('/alumnos/buscar', AlumnosController.getAlumnoByParameter);
router.get('/alumnos/filtrar', AlumnosController.filterAlumnosByTerm);
router.get('/reportes/conteo', ReportesController.getSubmissionsCount);
router.get('/reportes/filtrar', ReportesController.getSubmissionsPaginated);
router.get('/reportes/lista', ReportesController.getAllSubmissions);
router.get('/reportes/buscar/:id', ReportesController.getSubmissionById);
router.get('/reportes/conteo_area/:areaId', ReportesController.getSubmissionsCountByArea);
router.get('/reportes/filtro_area', ReportesController.getSubmissionsByArea);
router.get('/reportes/conteo_estudiante/:codigoAlumno', ReportesController.getSubmissionsCountByStudent);
router.get('/reportes/filtro_estudiante', ReportesController.getSubmissionsByStudent);
router.post('/reportes', ReportesController.createSubmission);
router.put('/reportes/:id', ReportesController.updateSubmission);
router.delete('/reportes/:id', ReportesController.deleteSubmission);
router.get('/reportes/estado/:status', ReportesController.getByStatus);
router.get('/reportes/conteo_estados', ReportesController.countByStatus);
router.get('/reportes/recientes', ReportesController.getRecent);
router.get('/reportes/ia', ReportesController.getAIGenerated);
router.post('/reportes/marcar_revisado', ReportesController.markAsReviewed);
router.get('/reportes/no_revisados', ReportesController.getUnreviewed);
router.get('/reportes/no_revisados/conteo/:areaId', ReportesController.countUnreviewedByArea);
router.get('/reportes/docentes', ReportesController.getDocenteReports);
router.get('/reportes/prioridad', ReportesController.getReportsWithPriority);
router.post('/reportes/docente', ReportesController.createDocenteSubmission);
router.get('/admin-users/admin-oro-with-areas', AdminUsersController.getAdminOroWithAreas);
router.put('/admin-users/:id', AdminUsersController.updateAdmin);
router.delete('/user-areas/:userId', UserAreasController.deleteUserAreas);
router.post('/user-areas', UserAreasController.insertUserAreas);

module.exports = router;